### ISSUE TITLE
How do I Host multiple swagger docs?

### ISSUE THREAD

**Issue by xxKeoxx** [marshmallow-code/flask-smorest#477]
Hi.  I am sorry if this is a duplicate, but I've been struggling for this for over a week and I can't find answers.

I've been able to have my endpoints versioned
Example: 
https://mysite/api/v1/foo
https://mysite/api/v2/foo

but I can't find a way to serve up 2 swagger docs ( one for each version ).
I want to do this:
https://mysite/swagger/v1/. <--- Shows only the V1 endpoints
https://mysite/swagger/v2/ <--- Shows only the v2 endpoints

I can get a single swagger doc to show the v1 and v2 endpoints together, but that's not what we want.

Can you help me figure this out?

**Comment by lafrech** [comment]
This should be addressed by #422.

**Comment by xxKeoxx** [comment]
@lafrech  - I am sorry I am probably missing something.  I have read over many of the threads linked in the one that as well, but I am still having problems getting this to work.  I am currently trying to do this:

```
from flask import Flask, request, redirect, current_app
from flask_smorest import Api
from app.apis.iaas_api_v1 import api_v1_parent
from app.apis.iaas_api_v2 import api_v2_parent
 
app = Flask(__name__)
 
app.config["PROPAGATE_EXCEPTIONS"] = True
app.config["API_TITLE"] = "My API"
app.config["OPENAPI_VERSION"] = "3.0.3"
app.config["OPENAPI_SWAGGER_UI_URL"] = https://cdn.jsdelivr.net/npm/swagger-ui-dist/
app.config["OPENAPI_SWAGGER_UI_CONFIG"] = {'supportedSubmitMethods': ['get']}
app.config["API_V1_OPENAPI_URL_PREFIX"] = "/swagger/v1"
app.config["API_V2_OPENAPI_URL_PREFIX"] = "/swagger/v2"

apiv1 = Api(app, config_prefix="API_V1_")
apiv2 = Api(app, config_prefix="API_V2_")

apiv1.register_blueprint(api_v1_parent)
apiv2.register_blueprint(api_v2_parent)
```


I get `unexpected keyword argument 'config_prefix'` when I start flask.

Am I doing something wrong here?

**Comment by lafrech** [comment]
`API_V1_OPENAPI_URL_PREFIX` doesn't work.

Things like this should be possible with #422, but it will take a different from and I haven't yet had the time to review/merge anyway.

Until then, the feature is not supported. (And #422 is about multiple API, not just multiple docs, but that makes sense because since the doc is mostly automatic, you wouldn't have different docs for the same API.)

**Comment by xxKeoxx** [comment]
Ok.  Thank you for the reply.  At least I know it's not something I am doing wrong.
